In [2]:
import numpy as np
import time

In [3]:
arr1=np.random.randn(8)
arr1

array([-0.03326954, -0.66249811, -0.22100981,  0.80378004, -0.52435697,
       -0.91028134, -0.08018507,  0.81328292])

In [15]:
arr2=np.random.randint(10,size=(3,3))
arr2

array([[0, 2, 0],
       [4, 8, 6],
       [4, 6, 1]])

In [19]:
arr3=np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr4=np.eye(3)
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
arr5=np.ones(4)
arr5

array([1., 1., 1., 1.])

In [77]:
si=int(input('enter size of matrix'))
x=np.random.randint(10,size=(si,si))
y=np.random.randint(10,size=(si,si))
print(x,'\n\n',y)

enter size of matrix10
[[8 0 3 1 4 6 7 9 8 5]
 [9 4 6 8 3 3 2 9 7 4]
 [5 3 7 0 2 8 7 7 4 3]
 [0 7 0 4 8 3 0 9 4 2]
 [2 4 5 8 0 5 4 6 8 3]
 [7 5 1 4 9 5 4 4 1 8]
 [1 1 7 2 1 3 7 1 6 6]
 [2 3 5 2 2 9 6 2 8 4]
 [1 0 4 0 3 1 3 1 8 4]
 [6 3 8 3 8 1 1 3 0 4]] 

 [[8 5 0 8 8 3 3 6 0 2]
 [9 1 9 8 3 5 9 0 4 9]
 [3 1 1 5 1 3 7 4 2 1]
 [6 2 8 5 4 3 0 5 7 2]
 [4 9 0 9 0 5 7 6 0 3]
 [5 6 6 9 7 3 2 4 4 3]
 [2 1 5 6 0 5 0 2 6 6]
 [7 9 4 5 4 8 9 5 9 2]
 [5 3 5 2 4 5 3 6 0 4]
 [2 1 9 6 7 7 6 9 8 0]]


In [80]:
def mul(m,n):
    r1=x.shape[0]
    c1=x.shape[1]
    r2=y.shape[0]
    c2=y.shape[1]
    mul=np.zeros(c1*r2).reshape(c1,r2)
    start2=time.time()
    for i in range(r1):
        for j in range (c2):
            mul[i][j]=0
            for k in range(c1):
                mul[i][j]+=x[i][k]*y[k][j]
            print(mul[i][j])
    end2=time.time()
    print("for loop",end2-start2)

print("MATRIX ADDITION\nMATRIX SUBTRACTION\nMATRIX MULTIPLICATION\n")
ans='Y'
while(ans=='Y'):
    choice=int(input('ENTER YOUR CHOICE'))
    if(choice==1 and x.shape[0]==y.shape[0] and x.shape[1]==y.shape[1]):
        print(x+y)
    if(choice==2 and x.shape[0]==y.shape[0] and x.shape[1]==y.shape[1]):
        print(x-y)
    if(choice==3 and x.shape[0]==y.shape[1] and x.shape[1]==y.shape[0]):
        start1=time.time()
        print(np.dot(x,y))
        end1=time.time()
        print("function",end1-start1,"\n")
        mul(x,y)
        ans=(input("want to continue?(Y/N)"));


MATRIX ADDITION
MATRIX SUBTRACTION
MATRIX MULTIPLICATION

ENTER YOUR CHOICE3
[[252 234 203 307 216 256 220 265 200 143]
 [311 224 241 323 235 258 258 275 221 152]
 [225 186 192 292 177 217 214 202 187 146]
 [221 200 187 240 124 202 230 167 165 138]
 [236 150 246 246 177 209 183 205 204 144]
 [246 211 221 341 199 234 233 246 194 146]
 [132  84 173 192 117 164 137 171 143 102]
 [197 146 216 260 169 193 166 196 158 145]
 [ 98  82 105 127  83 124 111 139  71  70]
 [185 157 118 253 124 166 210 188 118  92]]
function 0.0008757114410400391 

252.0
234.0
203.0
307.0
216.0
256.0
220.0
265.0
200.0
143.0
311.0
224.0
241.0
323.0
235.0
258.0
258.0
275.0
221.0
152.0
225.0
186.0
192.0
292.0
177.0
217.0
214.0
202.0
187.0
146.0
221.0
200.0
187.0
240.0
124.0
202.0
230.0
167.0
165.0
138.0
236.0
150.0
246.0
246.0
177.0
209.0
183.0
205.0
204.0
144.0
246.0
211.0
221.0
341.0
199.0
234.0
233.0
246.0
194.0
146.0
132.0
84.0
173.0
192.0
117.0
164.0
137.0
171.0
143.0
102.0
197.0
146.0
216.0
260.0
169.0
193.0
166.

In [49]:
print("1:ABSOLUTE VALUES\n2:NEGATIVE MATRIX\n\n")
ans='Y'
while(ans=='Y'):
    choice=int(input('ENTER YOUR CHOICE'))
    if(choice==1):
        print(np.abs(x))
    if(choice==2):
        print(-x)
#     if(choice==3):
#         print(np.dot(x,y))
    else:
        print()
    ans=(input("want to continue?(Y/N)"));

1:ABSOLUTE VALUES
2:NEGATIVE MATRIX


ENTER YOUR CHOICE6
NOT A VALID CHOICE
want to continue?(Y/N)n


In [34]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 