In [1]:
import numpy as np

# Creating two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matrix2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

In [2]:
# Transpose of a matrix
transpose1 = np.transpose(matrix1)
transpose2 = matrix2.T
print(transpose1)
print(transpose2)

[[1 4]
 [2 5]
 [3 6]]
[[ 7 10]
 [ 8 11]
 [ 9 12]]


In [3]:
# Addition of two matrices
print(matrix1 + matrix2)

[[ 8 10 12]
 [14 16 18]]


In [4]:
# Subtraction of two matrices
print(matrix1 - matrix2)

[[-6 -6 -6]
 [-6 -6 -6]]


In [5]:
# Multiplication of two matrices
print(np.dot(matrix1, matrix2.T))


[[ 50  68]
 [122 167]]
