In [1]:
import numpy as np
import time

In [2]:
arr1=np.random.randn(8)
arr1

array([-0.27615007, -0.74683951, -0.62904113,  0.16287828,  1.63304022,
       -0.88374455,  0.11433294, -0.37732292])

In [3]:
arr2=np.random.randint(10,size=(3,3))
arr2

array([[7, 6, 3],
       [7, 4, 2],
       [7, 5, 6]])

In [7]:
arr3=np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr4=np.eye(3)
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
arr5=np.ones(4)
arr5

array([1., 1., 1., 1.])