In [1]:
import numpy as np
import sys

In [2]:
# Compute the size of a matrix
matrix = np.random.randint(10, size=(3,3))
matrix_size = matrix.size
print("Size of the matrix:", matrix_size)

Size of the matrix: 9


In [3]:
# Size/length of a particular row/column
row_length = len(matrix[0])  # Length of the first row
column_length = len(matrix[:, 0])  # Length of the first column
print("Length of the first row:", row_length)
print("Length of the first column:", column_length)

Length of the first row: 3
Length of the first column: 3


In [4]:
# Load data from a text file
data = np.loadtxt("data.txt")
print("Loaded data:\n", data)

Loaded data:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [5]:
# Store matrix data to a text file
np.savetxt("output.txt", matrix, fmt="%d")

In [6]:
# Finding out variables and their features in the current scope
variables = list(globals().keys())
for var in variables:
    if not var.startswith("_"):
        print(var, sys.getsizeof(eval(var)))

In 120
Out 232
get_ipython 64
exit 48
quit 48
np 72
sys 72
matrix 156
matrix_size 28
row_length 28
column_length 28
data 120
