In [2]:
import numpy as np
# Take input from user for matrix 1
print("Enter elements for Matrix 1 (3x3):")
matrix1 = np.zeros((3, 3), dtype=int)
for i in range(3):
    for j in range(3):
        matrix1[i, j] = int(input())

# Take input from user for matrix 2
print("\nEnter elements for Matrix 2 (3x3):")
matrix2 = np.zeros((3, 3), dtype=int)
for i in range(3):
    for j in range(3):
        matrix2[i, j] = int(input())

# Perform operations on matrices
result_addition = matrix1 + matrix2
result_subtraction = matrix1 - matrix2
result_multiplication_elementwise = matrix1 * matrix2
result_multiplication_matrix = np.dot(matrix1, matrix2)

# Display results
print("\nMatrix Addition:")
print(result_addition)

print("\nMatrix Subtraction:")
print(result_subtraction)

print("\nElement-wise Matrix Multiplication:")
print(result_multiplication_elementwise)

print("\nMatrix Multiplication:")
print(result_multiplication_matrix)

Enter elements for Matrix 1 (3x3):
1
1
1
1
1
1
1
1
1

Enter elements for Matrix 2 (3x3):
1
1
1
1
1
1
1
1
1

Matrix Addition:
[[2 2 2]
 [2 2 2]
 [2 2 2]]

Matrix Subtraction:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Element-wise Matrix Multiplication:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Matrix Multiplication:
[[3 3 3]
 [3 3 3]
 [3 3 3]]
