In [1]:
import numpy as np
# matrix
matrix = np.array([[-1, 2, 3],
                   [4, -5, 6],
                   [7, 8, 9]])

In [2]:
#Converting matrix data to absolute values:
abs_matrix = np.abs(matrix)
print(abs_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
#Taking the negative of matrix values:
neg_matrix = -matrix
print(neg_matrix)

[[ 1 -2 -3]
 [-4  5 -6]
 [-7 -8 -9]]


In [4]:
#Adding/removing rows/columns from a matrix:
# Adding a row
new_row = np.array([1, 2, 3])
matrix_with_row_added = np.vstack((matrix, new_row))

# Removing a row
matrix_with_row_removed = np.delete(matrix, 0, axis=0)  # Removes the first row

# Adding a column
new_column = np.array([1, 2, 3]).reshape(-1, 1)
matrix_with_column_added = np.hstack((matrix, new_column))

# Removing a column
matrix_with_column_removed = np.delete(matrix, 0, axis=1)  # Removes the first column

print("Matrix_with_row_added\n",matrix_with_row_added)
print("Matrix_with_row_removed\n",matrix_with_row_removed)
print("Matrix_with_column_added\n",matrix_with_column_added)
print("Matrix_with_column_removed\n",matrix_with_column_removed)

Matrix_with_row_added
 [[-1  2  3]
 [ 4 -5  6]
 [ 7  8  9]
 [ 1  2  3]]
Matrix_with_row_removed
 [[ 4 -5  6]
 [ 7  8  9]]
Matrix_with_column_added
 [[-1  2  3  1]
 [ 4 -5  6  2]
 [ 7  8  9  3]]
Matrix_with_column_removed
 [[ 2  3]
 [-5  6]
 [ 8  9]]


In [5]:
#Finding the maximum or minimum values in a matrix or in a row/column:

print("Maximum value in the entire matrix : ")
print(np.max(matrix))

print("Minimum value in the entire matrix : ")
print(np.min(matrix))

print("Maximum value in each column : ")
print(np.max(matrix, axis=0))

print("Minimum value in each row : ")
print(np.min(matrix, axis=1))

Maximum value in the entire matrix : 
9
Minimum value in the entire matrix : 
-5
Maximum value in each column : 
[7 8 9]
Minimum value in each row : 
[-1 -5  7]


In [6]:
#Finding the sum of some/all elements in a matrix:

print("Sum of all elements in the matrix : ")
print(np.sum(matrix))

print("Sum of elements in each row : ")
print(np.sum(matrix, axis=1))

print("Sum of elements in each column : ")
print(np.sum(matrix, axis=0))

Sum of all elements in the matrix : 
33
Sum of elements in each row : 
[ 4  5 24]
Sum of elements in each column : 
[10  5 18]
